name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        file: 'results.sarif'
        level: warning
